### ISSUE TITLE
Focus on teaser

### ISSUE THREAD

**Issue by abrahammartin** [mrginglymus/campl-ng#2]
Hi!

the body of the "focus on" teaser at http://people.ds.cam.ac.uk/wac26/campl-ng/in_page_components/teasers/ has no left or right borders or padding (both to 0).

It looks a bit strange having no space between the text and photo on the left and the text and the border of the box on the right.

Looking at the CSS this seems to have been done intentionally, or am I missing something?

BTW, great job! I'm planning to use it in my next project.

**Comment by mrginglymus** [comment]
Well spotted; should be fixed now. Not sure how that one crept in...
